require("@nomicfoundation/hardhat-toolbox");

const fs = require("fs");
let mnemonic = fs.readFileSync(".secret").toString().trim();
let infuraProjectID = fs.readFileSync(".infura").toString().trim();

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  networks: {
    sepolia: {
      url: `https://sepolia.infura.io/v3/${infuraProjectID}`,  // URL for Sepolia network via Infura
      accounts: {
        mnemonic,
        path: "m/44'/60'/0'/0", // BIP-44 standard path for Ethereum wallets
        initialIndex: 0,  // Start at the first account generated by the mnemonic
        count: 20,  // Number of accounts to unlock
      },
    },
  },
  etherscan: {
    apiKey: fs.readFileSync(".etherscan").toString().trim(),
  },
  solidity: "0.8.20",
};
